---
title       : Classical Central Limit Theorem
subtitle    : 
author      : SH
job         : WorkerBee
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Introduction to the Developing Data Products Peer Assignment

This presentation is part of the peer assignment for Developing Data Products.  The assignment contains two parts
+ to create a data product application using **shiny**
+ to create a presentation related to the application using **slidify**

--- 

## The Application

To display the understanding of using **shiny** to build an application, a simple application called **Classical Central Limit Theorem** has been developed and deployed at [here](https://sereneho.shinyapps.io/Apps/)


---

## The Uses of the Application

The application allows the user to
+ Select the inputs like number of samples and number of bins
+ See the outputs displayed in a barplot and histogram 

---

## The Data

The application is based on the data was extracted from the 1974 Motor Trend US magazine.  It is a built-in data frame in R called mtcars.

---

## The End
* The is the end of presentation.  Thank you!
---